### ISSUE TITLE
Support Episerver 11

### ISSUE THREAD

**Issue by HenningKlokkeraasen** [davidknipe/MenuPin#4]
A release for Episerver 11 would be very appreciated :)

**Comment by davidknipe** [comment]
Hi Henning - watch this space. Support for 11 is definitely coming soon ;)

**Comment by davidknipe** [comment]
Hi Henning as you can see this is now supported in v11 as part of the core product :)

https://world.episerver.com/blogs/David-Knipe/Dates/2017/12/pin-the-top-menu-in-the-episerver-ui/
